version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ggtix_postgres
    restart: always
    environment:
      POSTGRES_USER: ggtix
      POSTGRES_PASSWORD: ggtixpassword
      POSTGRES_DB: ggtix_db
    ports:
      - "5432:5432"
      - "5433:5432" # In case 5432 is occupied on host
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
